name: Deploy Static Website to Azure

on:
  push:  # Trigger this workflow on every push to the repository

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest  # Specifies the OS for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Step to pull the latest code from the repository

      - name: Build and Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Token from GitHub Secrets
          app_location: "/"  # Location of your app source code
          output_location: "/"  # Location of your built app (typically / for static apps)
